export const productCategoryOptions = [
  { value: "Mobile", text: "Mobile" },
  { value: "Laptop", text: "Laptop" },
  { value: "Computer", text: "Computer" },
];

export const productSubCategoryOptions = [
  "News",
  "Sports",
  "Science",
  "Yoga",
  "People",
  "Nature",
  "City",
  "Jobs",
  "Travel",
  "Fashion",
  "Mobile",
  "Health",
  "Spirituality",
  "Asana",
  "Anxiety",
  "Tantra",
  "Ayurveda",
  "Skin",
  "Hair",
  "Acne",
  "Weight Loss",
  "Chakra",
  "Massage",
  "Sexual Healing",
  "Immunity",
  "Fitness",
  "Strength",
];
